# Site settings
title: Knowledge base
email: kb@unitycoders.co.uk
description: "Knowledge base for FOSS hackers."
baseurl: ""
url: "http://yourdomain.com"
github_username:  unitycoders

# Build settings
markdown: kramdown
permalink: pretty
